# Generated by Django 4.1.6 on 2023-02-08 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ename', models.CharField(max_length=250)),
                ('Email', models.EmailField(max_length=250)),
                ('Contact', models.CharField(max_length=30)),
                ('Emgcontact', models.CharField(max_length=30)),
                ('Address', models.TextField(max_length=500)),
                ('Position', models.CharField(max_length=250)),
                ('Dob', models.DateField(max_length=10)),
                ('MariialStatus', models.BooleanField()),
                ('Bloodgrp', models.CharField(max_length=10)),
                ('Jobtitle', models.CharField(max_length=100)),
                ('Workloc', models.TextField(max_length=500)),
                ('Date_of_Join', models.DateField()),
                ('Report_to', models.CharField(max_length=250)),
                ('Linkedin', models.URLField()),
                ('Profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
