# Generated by Django 4.1.6 on 2023-02-10 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp_Leave_appilcation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Apply_date', models.DateField()),
                ('Nature_of_leave', models.CharField(max_length=255)),
                ('First_day', models.DateField()),
                ('Last_day', models.DateField()),
                ('Number_of_days', models.SmallIntegerField()),
                ('Empid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ems.employee')),
            ],
        ),
    ]
