# Generated by Django 4.1.6 on 2023-02-10 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0002_emp_leave_appilcation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emp_leave_appilcation',
            name='Apply_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
