# Generated by Django 4.1.6 on 2023-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0003_alter_emp_leave_appilcation_apply_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='emp_leave_appilcation',
            name='LeaveStatus',
            field=models.IntegerField(default=2),
        ),
    ]
