# Generated by Django 4.1.6 on 2023-02-11 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ems', '0004_emp_leave_appilcation_leavestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='Date_of_Join',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='Dob',
            field=models.DateField(max_length=10, null=True),
        ),
    ]
