# Generated by Django 4.1.6 on 2023-02-14 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ems', '0005_employee_user_alter_employee_date_of_join_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='MariialStatus',
            new_name='MaritalStatus',
        ),
    ]
